#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
TEMPLATE="$DIR/notification.json"
URL='http://localhost:16666/notify/trigger/'

if [[ "$1" == "" || "$2" == "" ]]; then
  echo 'Usage: notify title message [id] [recipient]'
  exit 1
fi

title="$1"
msg="$2"
id="$3"

if [[ "$4" != "" ]]; then
  recipient="$4"
else
  recipient='giftig-client'
fi

tmp="$(mktemp /tmp/gnotify-tests.XXXXXX)"
sed -E \
  -e "s|\{\{ id \}\}|$id|g" \
  -e "s|\{\{ title \}\}|$title|g" \
  -e "s|\{\{ message \}\}|$msg|g" \
  -e "s|\{\{ time \}\}|$(date --utc +'%Y-%m-%dT%H:%M:59Z')|g" \
  -e "s|\{\{ recipient \}\}|$recipient|g" \
  $TEMPLATE > $tmp

curl \
  -X POST \
  -H 'Content-Type: application/json' \
  -d "@$tmp" \
  "$URL" \
  -D -
echo ''
